# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: raft.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nraft.proto\"b\n\x12RequestVoteRequest\x12\x0c\n\x04term\x18\x01 \x01(\x05\x12\x13\n\x0b\x63\x61ndidateId\x18\x02 \x01(\x05\x12\x14\n\x0clastLogIndex\x18\x03 \x01(\x05\x12\x13\n\x0blastLogTerm\x18\x04 \x01(\x05\"3\n\x13RequestVoteResponse\x12\x0c\n\x04term\x18\x01 \x01(\x05\x12\x0e\n\x06result\x18\x02 \x01(\x08\"\x8f\x01\n\x12\x41ppendEntryRequest\x12\x0c\n\x04term\x18\x01 \x01(\x05\x12\x11\n\tleaaderId\x18\x02 \x01(\x05\x12\x14\n\x0cprevLogIndex\x18\x03 \x01(\x05\x12\x13\n\x0bprevLogTerm\x18\x04 \x01(\x05\x12\x17\n\x07\x65ntries\x18\x05 \x03(\x0b\x32\x06.Entry\x12\x14\n\x0cleaderCommit\x18\x06 \x01(\x05\"8\n\x05\x45ntry\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x12\n\ntermNumber\x18\x02 \x01(\x05\x12\x0f\n\x07message\x18\x03 \x01(\t\"6\n\x15\x41ppendEntriesResponse\x12\x0c\n\x04term\x18\x01 \x01(\x05\x12\x0f\n\x07success\x18\x02 \x01(\x08\"\x0e\n\x0c\x45mptyRequest\"\"\n\x0fSuspendResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\"6\n\x11GetLeaderResponse\x12\x10\n\x08leaderId\x18\x01 \x01(\x05\x12\x0f\n\x07\x61\x64\x64ress\x18\x02 \x01(\t\" \n\x0eSuspendRequest\x12\x0e\n\x06period\x18\x01 \x01(\x05\"\x1c\n\rGetValRequest\x12\x0b\n\x03key\x18\x01 \x01(\t\"0\n\x0eGetValPesponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\r\n\x05value\x18\x02 \x01(\t\"+\n\rSetValRequest\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t\"!\n\x0eSetValResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x32\xb9\x02\n\x0bRaftService\x12\x38\n\x0bRequestVote\x12\x13.RequestVoteRequest\x1a\x14.RequestVoteResponse\x12<\n\rAppendEntries\x12\x13.AppendEntryRequest\x1a\x16.AppendEntriesResponse\x12.\n\tGetLeader\x12\r.EmptyRequest\x1a\x12.GetLeaderResponse\x12,\n\x07Suspend\x12\x0f.SuspendRequest\x1a\x10.SuspendResponse\x12)\n\x06SetVal\x12\x0e.SetValRequest\x1a\x0f.SetValResponse\x12)\n\x06GetVal\x12\x0e.GetValRequest\x1a\x0f.GetValPesponseb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'raft_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _REQUESTVOTEREQUEST._serialized_start=14
  _REQUESTVOTEREQUEST._serialized_end=112
  _REQUESTVOTERESPONSE._serialized_start=114
  _REQUESTVOTERESPONSE._serialized_end=165
  _APPENDENTRYREQUEST._serialized_start=168
  _APPENDENTRYREQUEST._serialized_end=311
  _ENTRY._serialized_start=313
  _ENTRY._serialized_end=369
  _APPENDENTRIESRESPONSE._serialized_start=371
  _APPENDENTRIESRESPONSE._serialized_end=425
  _EMPTYREQUEST._serialized_start=427
  _EMPTYREQUEST._serialized_end=441
  _SUSPENDRESPONSE._serialized_start=443
  _SUSPENDRESPONSE._serialized_end=477
  _GETLEADERRESPONSE._serialized_start=479
  _GETLEADERRESPONSE._serialized_end=533
  _SUSPENDREQUEST._serialized_start=535
  _SUSPENDREQUEST._serialized_end=567
  _GETVALREQUEST._serialized_start=569
  _GETVALREQUEST._serialized_end=597
  _GETVALPESPONSE._serialized_start=599
  _GETVALPESPONSE._serialized_end=647
  _SETVALREQUEST._serialized_start=649
  _SETVALREQUEST._serialized_end=692
  _SETVALRESPONSE._serialized_start=694
  _SETVALRESPONSE._serialized_end=727
  _RAFTSERVICE._serialized_start=730
  _RAFTSERVICE._serialized_end=1043
# @@protoc_insertion_point(module_scope)
